# Generated by Django 4.2.24 on 2025-09-25 10:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_desconto', models.CharField(choices=[('PERCENTUAL', 'Percentual'), ('FIXO', 'Fixo')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID público e seguro para a URL da loja', unique=True)),
                ('nome', models.CharField(help_text='Nome fantasia do estabelecimento', max_length=100)),
                ('cnpj', models.CharField(help_text='CNPJ da loja (apenas números)', max_length=18, unique=True)),
                ('nome_proprietario', models.CharField(help_text='Nome completo do dono da loja', max_length=100)),
                ('email', models.EmailField(help_text='Email de contato da loja', max_length=100)),
                ('telefone', models.CharField(help_text='Telefone/WhatsApp de contato da loja', max_length=20)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('ativa', models.BooleanField(default=False, help_text='Interruptor geral. Se desmarcado, a loja fica offline.')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dia_vencimento_mensalidade', models.IntegerField(blank=True, help_text='O dia do mês para o vencimento da fatura (de 1 a 31).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.loja')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('endereco_rua', models.CharField(default='', max_length=255)),
                ('endereco_numero', models.CharField(default='', max_length=20)),
                ('endereco_bairro', models.CharField(default='', max_length=100)),
                ('endereco_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('troco_para', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_preparo', 'Em Preparo'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='recebido', max_length=20)),
                ('data_hora_pedido', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cupom')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entregador')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapagamento')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.loja')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
                ('produtos', models.ManyToManyField(to='core.produto')),
            ],
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='core.loja'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregadores', to='core.loja'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='core.loja'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.loja'),
        ),
        migrations.CreateModel(
            name='AcessoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('DONO', 'Dono'), ('ATENDENTE', 'Atendente')], max_length=20)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'loja')},
            },
        ),
    ]
