# Generated by Django 4.2.24 on 2025-10-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
