# Generated by Django 4.2.24 on 2025-10-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
